In [43]:
import numpy as np
import pandas as pd
import seaborn as sns

In [44]:
df = sns.load_dataset('iris')
df.head(5)

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [45]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [46]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=1)

In [47]:

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)


from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))



Accuracy of Logistic Regression 0.9666666666666667
Accuracy of Decision Trees 0.9666666666666667


In [ ]:
# for logistic reg
confusion_matrix(y_test,y_pred1)

array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]])

In [49]:
# for DT reg
confusion_matrix(y_test,y_pred2)

array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]])

In [50]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2
result.sample(10)


,Actual Label,Logistic Regression Prediction,Decision Tree Prediction
44,0,0,0
98,1,1,1
35,0,0,0
5,0,0,0
131,2,2,2
141,2,2,2
51,1,1,1
40,0,0,0
73,1,1,1
66,1,1,1


In [51]:

from sklearn.metrics import precision_score,recall_score
precision_score(y_test,y_pred1,average=None)

array([1.        , 1.        , 0.85714286])

In [52]:
recall_score(y_test,y_pred1,average=None)

array([1.        , 0.92307692, 1.        ])