In [1]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [2]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)
len(tokenizer.word_index)

17

In [4]:
sequence = tokenizer.texts_to_sequences(docs)
sequence

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [5]:
from keras.utils import pad_sequences
sequence = pad_sequences(sequence,padding='post')
sequence

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]])

In [7]:
from keras import Sequential
from keras.layers import Embedding
model =Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 5, 2)              34        
                                                                 
Total params: 34
Trainable params: 34
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile('adam','accuracy')

In [9]:
pred = model.predict(sequence)
print(pred)

1/1 [==============================] - 0s 168ms/step
[[[ 3.82294096e-02 -3.74053828e-02]
  [ 7.02941418e-03  2.03003772e-02]
  [ 4.35178988e-02  3.74674909e-02]
  [ 4.35178988e-02  3.74674909e-02]
  [ 4.35178988e-02  3.74674909e-02]]

 [[ 7.02941418e-03  2.03003772e-02]
  [ 7.02941418e-03  2.03003772e-02]
  [ 4.35178988e-02  3.74674909e-02]
  [ 4.35178988e-02  3.74674909e-02]
  [ 4.35178988e-02  3.74674909e-02]]

 [[-3.25501338e-02  1.92549936e-02]
  [-3.25501338e-02  1.92549936e-02]
  [ 4.39110063e-02  1.36908330e-02]
  [ 4.35178988e-02  3.74674909e-02]
  [ 4.35178988e-02  3.74674909e-02]]

 [[-6.13080338e-03  3.15503813e-02]
  [-3.89982387e-03  1.55211575e-02]
  [-6.13080338e-03  3.15503813e-02]
  [ 7.02941418e-03  2.03003772e-02]
  [-6.13080338e-03  3.15503813e-02]]

 [[ 5.48512861e-03 -2.78474819e-02]
  [-1.40996575e-02  3.46861370e-02]
  [-9.81241465e-06 -4.34758663e-02]
  [ 1.75987557e-03 -1.25323534e-02]
  [ 4.35178988e-02  3.74674909e-02]]

 [[-3.72762568e-02  3.70970480e-02]
 

In [10]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [11]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [12]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [13]:
X_train.shape

(25000, 50)

In [16]:
model = Sequential()
model.add(Embedding(10000, 2 ,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 21,153
Trainable params: 21,153
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=2,validation_data=(X_test,y_test))

Epoch 1/2
782/782 [==============================] - 131s 162ms/step - loss: 0.6706 - acc: 0.5589 - val_loss: 0.5072 - val_acc: 0.7528
Epoch 2/2
782/782 [==============================] - 133s 170ms/step - loss: 0.4350 - acc: 0.8021 - val_loss: 0.4177 - val_acc: 0.8099
