### Numpy array operation

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,12)
print("basic slicing: ",arr[2:7])
print("with step: ",arr[1:7:2])
print("negative index: ",arr[-5])

basic slicing:  [2 3 4 5 6]
with step:  [1 3 5]
negative index:  7


In [14]:
twod = np.arange(9).reshape((3,3))
print(twod)
print("any specific element: ",twod[1,1])
print("1st row : ",twod[0])
print("2nd coloum: "  , twod[:,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
any specific element:  4
1st row :  [0 1 2]
2nd coloum:  [1 4 7]


### sorting

In [23]:
unsorted = np.array([1,4,2,6,8,5,2,9])
print("sorted array ",np.sort(unsorted))

unsorted2d = np.array([[1,4,2],
                     [3,4,1]])
print("sorted array", np.sort(unsorted2d, axis = 0))
print("sorted array", np.sort(unsorted2d, axis = 1))

sorted array  [1 2 2 4 5 6 8 9]
sorted array [[1 4 1]
 [3 4 2]]
sorted array [[1 2 4]
 [1 3 4]]


### filter and filter with mask

In [27]:
numbers = np.arange(10)
evenNumbers = numbers[numbers%2 == 0]
print(evenNumbers)

# with mask
mask = numbers>3
print(numbers[mask])

[0 2 4 6 8]
[4 5 6 7 8 9]


### fancy indexing vs np.where()


In [ ]:
indices =[0,2,4]
print(numbers[indices])

where_result = np.where(numbers%2 == 0)
print(numbers[where_result])


[0 2 4]
[0 2 4 6 8]


In [32]:
condition_array = np.where(numbers%2 == 0,"true","False")
print(condition_array)

['true' 'False' 'true' 'False' 'true' 'False' 'true' 'False' 'true'
 'False']


### adding or removeing data

In [33]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


### array compatibilty


In [34]:
a = np.array([1,2,3])
b = np.array([1,2,3,5])
c = np.array([3,2,3])

print("compatibily status",a.shape == b.shape)
print("compatibily status",a.shape == c.shape)

compatibily status False
compatibily status True


In [48]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [49]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print(deleted)

[1 2 4 5]
