## learn about numpy 

In [ ]:
import numpy as np

### creating array from list

In [ ]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2],[3,4]])
print(arr_2d)

[1 2 3 4 5]
[[1 2]
 [3 4]]


## list vs numpy array

In [8]:
py_list = [1,2,3]
print("list multipication: ",py_list)

np_array = np.array([1,2,3])
print("array multipication:",np_array)

import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("list operation time: ",time.time() - start)
start = time.time()
np_array = np.arange(10000000) * 2
print("np_array operation time: ",time.time() - start)


list multipication:  [1, 2, 3]
array multipication: [1 2 3]
list operation time:  0.7731931209564209
np_array operation time:  0.058655500411987305


### creating a array

In [14]:
zeros = np.zeros((3,4))
print(zeros)

once = np.ones((2,3))
print(once)

full = np.full((2,3),7)
print(full)

random = np.random.random((2,3)) * 100
print(random)

sequence = np.arange(0,11, 2)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[72.56159723 94.63293448 56.00985752]
 [85.67592242 30.78023268 28.14136675]]
[ 0  2  4  6  8 10]


### vector,matrix and tensor

In [15]:
vector = np.array([1,2])
matrix = np.array([[1,2],[3,4]])
tensor = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(vector)
print(matrix)
print(tensor)

[1 2]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


### array properties

In [16]:
arr = np.array([[1,2,3],
               [4,5,6]])
print("shape ",arr.shape)
print("dimension ",arr.ndim) # important
print("size ",arr.size)
print("datatype",arr.dtype)

shape  (2, 3)
dimension  2
size  6
datatype int64


### array reshaping

In [22]:
arr = np.arange(12)

reshaped = arr.reshape((2,6))
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

# ravel ( return view instant of copy)
raveled = reshaped.ravel()
print(raveled)

#transpose
print(reshaped.T)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
