In [3]:
import numpy as np

### Topic 28: Matrix Diagonalization and the Spectral Theorem


ML Math Notes: Diagonalization & The Spectral Theorem

**Core Guarantee:** If a matrix is symmetric ($A = A^T$), it is diagonalizable as $A = Q \Lambda Q^T$, yielding **real eigenvalues** and **perfectly orthogonal eigenvectors**.

**1. The $O(N)$ Exponentiation Cheat Code**
* **Application:** Simulating future steps in Markov Decision Processes (RL) or Graph Neural Networks.
* **The Bottleneck:** Standard matrix multiplication for $A^{100}$ scales at a catastrophic $O(N^3)$.
* **The Bypass:** $A^{100} = Q \Lambda^{100} Q^T$. Because $\Lambda$ is a diagonal matrix, $\Lambda^{100}$ simply requires raising the scalar diagonal elements to the 100th power, reducing the core operation to $O(N)$.

**2. Feature Disentanglement (Zero Correlation)**
* **Application:** Principal Component Analysis (PCA) and dimensionality reduction.
* **The Mechanism:** The Spectral Theorem guarantees the eigenvectors of our Covariance matrix are orthogonal.
* **The ML Impact:** In data science, orthogonal vectors mathematically guarantee **zero linear correlation**. Projecting data onto these eigenvectors perfectly disentangles the features (PC1 and PC2 will have 0 correlation).

In [ ]:
np.random.seed(42)
A = np.random.randn(3,3)
symmetric_A = A @ A.T

eigenvalue,eigenvector = np.linalg.eigh(symmetric_A)

# np.diag() converts a 1D array into a 2D diagonal matrix
Lambda =  np.diag(eigenvalue) # lambda is diagonal matrix

# spectral theorem reconstruction
# A = Q @ Lambda @ Q^T
reconstructed_A = eigenvector @ Lambda @ eigenvector.T

is_perfect = np.allclose(symmetric_A,reconstructed_A)
print(is_perfect)


[[0.68534241 0.63723771 0.37423535]
 [0.63723771 2.42926786 2.33541214]
 [0.37423535 2.33541214 3.30327538]]
[[0.68534241 0.63723771 0.37423535]
 [0.63723771 2.42926786 2.33541214]
 [0.37423535 2.33541214 3.30327538]]
True


In [9]:
np.random.seed(42)
A = np.random.randn(5, 5)
Transition_Matrix = A @ A.T # symmetric 

eigenvalue_1 , eigenvector_1 = np.linalg.eigh(Transition_Matrix)

Lambda_1 = np.diag(eigenvalue_1)
# Lambda_50 = np.linalg.matrix_power(Lambda,50) wrong 
Lambda_50 = Lambda_1 ** 50

reconstructed_matrix = eigenvector_1 @ Lambda_50 @ eigenvector_1.T

test = np.linalg.matrix_power(Transition_Matrix,50)

is_perfect_1 = np.allclose(test,reconstructed_matrix)
print(is_perfect_1)




True


### Topic 29: Singular Value Decomposition (SVD) Matrix Factorization

**Core Guarantee:** ANY matrix (even non-square) can be decomposed into $A = U \Sigma V^T$.
* $U$ and $V^T$ are orthogonal matrices (rotations/reflections).
* $\Sigma$ is a diagonal matrix of **Singular Values** (sorted descending).

**1. Truncated SVD (Image/Data Compression)**
* **Concept:** The largest singular values hold the most information. 
* **ML Application:** If you keep only the top $k$ singular values (and their corresponding vectors in $U$ and $V^T$), you can perfectly approximate the original matrix with a fraction of the memory.

**2. Recommender Systems (Latent Semantics)**
* **Concept:** Factoring a sparse User-Item matrix reveals hidden "latent" features (like movie genres or shopper habits).

In [10]:
A = np.random.randn(400 , 10)

# 1.SVD 
U , singularValue , V_T = np.linalg.svd(A , full_matrices= False)
print("shape of U: ",U.shape)
print("shape of sigma (1D): ",singularValue.shape)
print("shape of V_T: ",V_T.shape)

# 2.reconstruct 
sigma_matrix = np.diag(singularValue)

reconstructed_2 = U @ sigma_matrix @ V_T
is_perfect_2 = np.allclose(A,reconstructed_2)
print(is_perfect_2)

shape of U:  (400, 10)
shape of sigma (1D):  (10,)
shape of V_T:  (10, 10)
True


In [17]:


np.random.seed(42)
# A 500x500 "Image" Matrix
image_matrix = np.random.randn(500, 500)

U_3 , singularValue_3 , V_T_3 = np.linalg.svd(image_matrix,full_matrices=True)
slice_U_3 = U_3[: , :20]

slice_singularValue = singularValue_3[: 20]
diagonal_matrix = np.diag(slice_singularValue)
slice_V_T_3 = V_T_3[:20 , :]

compressed_image = slice_U_3 @ diagonal_matrix @ slice_V_T_3
print(compressed_image)

[[-0.05540308 -0.55732499  0.16479536 ...  0.14068991 -0.48188734
   0.0789307 ]
 [-0.7402583   0.75264884 -0.16776929 ...  0.09038752  0.05051289
  -0.31430432]
 [ 0.0293703   0.34048835  0.05689062 ...  0.0611677   0.3986264
   0.11540234]
 ...
 [ 0.21609174  0.05576493 -0.2257865  ... -0.28641128 -0.28568821
   0.12092734]
 [ 0.40920373 -0.24212845  0.4283312  ... -0.02398869  0.16770008
   0.43992699]
 [-0.21559124  1.58288833 -0.49279055 ... -0.47818461  0.49242729
   0.01831182]]
