In [4]:
import numpy as np
import matplotlib.pyplot as plt

### Topic 23: Systems of Linear Equations (Gaussian Elimination, Rank calculation). 



The Machine Learning Translation:
In ML, the equation $Ax = b$ is written as $Xw = y$.
- $X$ is your dataset (matrix of features).
- $y$ is your target output (vector of labels/prices).
- $w$ is the weights of your model.


In [10]:
# --- 1. THE EXACT SOLUTION (Perfectly Square System) ---
# 3 equations, 3 variables
# 2x + 3y + z = 10
#  x -  y + 2z = 5
# 3x + 2y -  z = 4

A = np.array([
    [2,  3,  1],
    [1, -1,  2],
    [3,  2, -1]
])
b = np.array([10,5,4])

rank = np.linalg.matrix_rank(A)
print("rank of matrix A is : ",rank)

if rank == A.shape[1]:
    exact_weights = np.linalg.solve(A,b)  # use for only in square solution
    print("exact solution(x,y,z)", exact_weights)
print("\n_________________________________________________\n")

# --- 2. THE MACHINE LEARNING WAY (Overdetermined System) ---
# 5 equations (data points), 2 variables (features: intercept and slope)
# This is a basic Linear Regression setup.
X_data = np.array([
    [1, 1], # [intercept, x1]
    [1, 2], 
    [1, 3], 
    [1, 4], 
    [1, 5]
])
y_targets = np.array([2.1,3.8,6.2,8.1,10.5])

approx_weights , residuals, rank_lstsq,singular_vals = np.linalg.lstsq(X_data, y_targets)
print(f"\nLeast Squares Weights (Intercept, Slope): {approx_weights}")
print(f"Sum of Squared Errors (Residuals): {residuals}")
print(rank_lstsq)
print(singular_vals)

rank of matrix A is :  3
exact solution(x,y,z) [1.15 1.65 2.75]

_________________________________________________


Least Squares Weights (Intercept, Slope): [-0.19  2.11]
Sum of Squared Errors (Residuals): [0.131]
2
[7.69121313 0.91936964]


when run np.linalg.lstsq(X,y) return 4 data 
- solution approx_weights A 1D array containing the optimal weights ($w$) that minimize the error in the equation $Xw = y$.
- error    residuals An array containing the Sum of Squared Errors (SSE). It calculates the vertical distance from every real data point to your line of best fit, squares those distances, and adds them all up.
- matrix rank  rank_lstsq  An integer representing the rank of your feature matrix $X$.
- dimensional strngths  singular_vals  An array of the singular values of matrix $X$, sorted from largest to smallest.

In [21]:
np.random.seed(42) # For reproducible results
house_size = np.random.randint(800, 4000, 100)
house_age = np.random.randint(1, 50, 100)

true_prices = (150 * house_size) - (1000 * house_age) + 50000 + np.random.normal(0, 10000, 100)
once = np.ones(100)
feature_matrix = np.column_stack((once,house_size,house_age))

solution,error,rank_matrix,dimensinal_strenght = np.linalg.lstsq(feature_matrix,true_prices)
print(solution)

[48984.58456523   148.96000534  -835.47323551]


### Topic 24: Special Structures (Identity, Orthogonal, Symmetric matrices).

Special Matrix Structures in Machine Learning

* **Identity Matrices ($I$):** Used to initialize weights in RNNs to pass memory forward perfectly unchanged, preventing gradients from vanishing or exploding over long time steps.
* **Orthogonal Matrices ($Q$):** Rotates or reflects space without scaling ($Q^T Q = I$). Used to initialize deep neural networks to perfectly preserve data variance across hundreds of layers.
* **Symmetric Matrices ($A = A^T$):** The engine of ML (Covariance and Hessian matrices). The Spectral Theorem guarantees they have real eigenvalues and orthogonal eigenvectors, making algorithms like PCA mathematically possible.

In [25]:
# 1.idntity matrix

I = np.eye(3)
print("identity matrix \n",I)

# 2. orthonogal matrices
theta = np.radians(30)
Q = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta),  np.cos(theta)]
])

## Verification: Q.T @ Q must equal the Identity Matrix.
is_orthogonal = np.allclose(Q.T @ Q, np.eye(2))
print("is orthogonal",is_orthogonal)

# 3.symmetric matrix
A = np.random.randn(3,5)
Symmetric_Matrix = A @ A.T

# Verification: The matrix must exactly equal its transpose.
is_symmetric = np.allclose(Symmetric_Matrix, Symmetric_Matrix.T)
print(f"generated matrix symmetric {is_symmetric}")


identity matrix 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
is orthogonal True
generated matrix symmetric True


In [36]:
X = np.random.randn(1000, 3)

average = np.mean(X, axis = 0)

X_centered = X - average

X_T_centered = X_centered.T

C = (1/(1000-1))*(X_T_centered @ X_centered)

C_T = C.T

symmetric = np.allclose(C,C_T)
print(symmetric)



True
